name: "Hello Actions"
description: "Greet someone"
author: "saptarshi3.14@gmail.com"

inputs:
        my_name:
                description: "Who to greet"
                required: true
                default: "world"
runs:
        using: "docker" 
        image: "Dockerfile"

branding:
        icon: "mic"
        color: "purple"        

